<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

class Divi_Dash_API_Response_Status
{
    public const NOT_FETCHED = 'NOT_FETCHED';

    public const SITE_NOT_MULTISITE = 'SITE_NOT_MULTISITE';

    public const PLUGIN_IS_NETWORK_ACTIVATED = 'PLUGIN_IS_NETWORK_ACTIVATED';

    public const PLUGIN_NOT_INSTALLED = 'PLUGIN_NOT_INSTALLED';

    public const PLUGIN_ALREADY_ACTIVATED = 'PLUGIN_ALREADY_ACTIVATED';

    public const PLUGIN_ALREADY_INSTALLED = 'PLUGIN_ALREADY_INSTALLED';

    public const PLUGIN_ACTIVATED = 'PLUGIN_ACTIVATED';

    public const PLUGIN_ACTIVATION_FAILED = 'PLUGIN_ACTIVATION_FAILED';

    public const PLUGIN_ALREADY_DEACTIVATE = 'PLUGIN_ALREADY_DEACTIVATE';

    public const PLUGIN_DEACTIVATED = 'PLUGIN_DEACTIVATED';

    public const PLUGIN_DEACTIVATION_FAILED = 'PLUGIN_DEACTIVATION_FAILED';

    public const PLUGIN_ALREADY_NETWORK_ACTIVATE = 'PLUGIN_ALREADY_NETWORK_ACTIVATE';

    public const PLUGIN_NETWORK_ACTIVATED = 'PLUGIN_NETWORK_ACTIVATED';

    public const PLUGIN_NETWORK_ACTIVATION_FAILED = 'PLUGIN_NETWORK_ACTIVATION_FAILED';

    public const PLUGIN_ALREADY_NETWORK_DEACTIVATE = 'PLUGIN_ALREADY_NETWORK_DEACTIVATE';

    public const PLUGIN_NETWORK_DEACTIVATED = 'PLUGIN_NETWORK_DEACTIVATED';

    public const PLUGIN_NETWORK_DEACTIVATION_FAILED = 'PLUGIN_NETWORK_DEACTIVATION_FAILED';

    public const PLUGIN_DELETED = 'PLUGIN_DELETED';

    public const PLUGIN_DELETION_FAILED = 'PLUGIN_DELETION_FAILED';

    public const PLUGIN_ACTIVE = 'PLUGIN_ACTIVE';

    public const PLUGIN_INVALID_LICENSE = 'PLUGIN_INVALID_LICENSE';

    // Theme statuses
    public const THEME_NOT_ALLOWED_FOR_MULTISITE = 'THEME_NOT_ALLOWED_FOR_MULTISITE';

    public const THEME_ALREADY_ACTIVE = 'THEME_ALREADY_ACTIVE';

    public const THEME_ALREADY_INSTALLED = 'THEME_ALREADY_INSTALLED';

    public const THEME_ACTIVATED = 'THEME_ACTIVATED';

    public const THEME_ACTIVATION_FAILED = 'THEME_ACTIVATION_FAILED';

    public const THEME_ALREADY_NETWORK_ACTIVE = 'THEME_ALREADY_NETWORK_ACTIVE';

    public const THEME_NETWORK_ACTIVATED = 'THEME_NETWORK_ACTIVATED';

    public const THEME_NETWORK_ACTIVATION_FAILED = 'THEME_NETWORK_ACTIVATION_FAILED';

    public const THEME_ALREADY_NETWORK_DEACTIVE = 'THEME_ALREADY_NETWORK_DEACTIVE';

    public const THEME_NETWORK_DEACTIVATED = 'THEME_NETWORK_DEACTIVATED';

    public const THEME_NETWORK_DEACTIVATION_FAILED = 'THEME_NETWORK_DEACTIVATION_FAILED';

    public const THEME_DELETED = 'THEME_DELETED';

    public const THEME_DELETION_FAILED = 'THEME_DELETION_FAILED';

    public const THEME_NOT_INSTALLED = 'THEME_NOT_INSTALLED';

    public const THEME_ACTIVE = 'THEME_ACTIVE';

    public const THEME_INVALID_LICENSE = 'THEME_INVALID_LICENSE';

    // User statuses
    public const ADMIN_USER = 'ADMIN_USER';

    public const DELETED = 'DELETED';

    public const NOT_DELETED = 'NOT_DELETED';

    public const NOT_EXIST = 'NOT_EXIST';

    public const EDITED = 'EDITED';

    public const NOT_EDITED = 'NOT_EDITED';

    public const ADMIN_USER_ROLE = 'ADMIN_USER_ROLE';

    public const ADDED = 'ADDED';

    public const NOT_ADDED = 'NOT_ADDED';

    public const USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS';

    public const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';

    public const CONFIRMATION_EMAIL_SENT = 'CONFIRMATION_EMAIL_SENT';

    // Other statuses
    public const UPDATED = 'UPDATED';

    public const NOT_UPDATED = 'NOT_UPDATED';

    public const FETCHED = 'FETCHED';

    public const ROLES_FETCHED = 'ROLES_FETCHED';

    public const ROLES_NOT_FETCHED = 'ROLES_NOT_FETCHED';

    public const SERVER_DATA_FETCHED = 'SERVER_DATA_FETCHED';

    public const SERVER_DATA_NOT_FETCHED = 'SERVER_DATA_NOT_FETCHED';

    public const OPTIMIZATION_FETCHED = 'OPTIMIZATION_FETCHED';

    public const OPTIMIZATION_NOT_FETCHED = 'OPTIMIZATION_NOT_FETCHED';

    public const SITE_USER_DATA_FETCHED = 'SITE_USER_DATA_FETCHED';

    public const SITE_USER_DATA_NOT_FETCHED = 'SITE_USER_DATA_NOT_FETCHED';

    public const SUBSITES_FETCHED = 'SUBSITES_FETCHED';

    public const SUBSITES_NOT_FETCHED = 'SUBSITES_NOT_FETCHED';

    public const SUBSITE_NOT_FOUND = 'SUBSITE_NOT_FOUND';

    public const INSTALLED = 'INSTALLED';

    public const NOT_INSTALLED = 'NOT_INSTALLED';

    public const SITE_USER_INFO_FETCHED = 'SITE_USER_INFO_FETCHED';

    public const SITE_USER_INFO_NOT_FETCHED = 'SITE_USER_INFO_NOT_FETCHED';

    public const SITE_DISCONNECTED = 'SITE_DISCONNECTED';
}
